const cfg=JSON.parse(document.getElementById('configData').textContent);
const $=id=>document.getElementById(id);
const cover=$('cover'),experience=$('experience'),viewport=$('viewport'),editor=$('editor');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function apply(){document.querySelectorAll('[data-key]').forEach(el=>{if(typeof cfg[el.dataset.key]==='string')el.textContent=cfg[el.dataset.key]});for(const [key,value] of Object.entries(cfg.assets)){if(value.startsWith('data:image/')){document.querySelectorAll(`[data-asset="${key}"]`).forEach(el=>el.setAttribute('href',value));if(key==='panorama')document.querySelector('[data-cover]').src=value}}if(reduced)document.querySelectorAll('animate').forEach(el=>el.setAttribute('dur','.001s'))}
apply();
function go(n){const scale=$('journeyArt').clientHeight/900;viewport.scrollTo({left:[0,1200,2350,3450][n]*scale,behavior:reduced?'instant':'smooth'})}
$('enter').onclick=()=>{cover.hidden=true;experience.hidden=false;viewport.scrollLeft=0;if(matchMedia('(orientation: portrait)').matches)$('rotateHint').hidden=false};
$('ready').onclick=()=>{$('rotateHint').hidden=true};
$('home').onclick=()=>{experience.hidden=true;cover.hidden=false};
$('reset').onclick=()=>{const art=$('journeyArt');art.replaceWith(art.cloneNode(true));apply();go(0)};
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>go(Number(b.dataset.scene)));
viewport.addEventListener('scroll',()=>{const scale=$('journeyArt').clientHeight/900;const pos=viewport.scrollLeft/scale;const n=pos>3000?3:pos>1800?2:pos>650?1:0;document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',Number(b.dataset.scene)===n))},{passive:true});
viewport.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.cl-hit')){e.preventDefault();e.target.closest('.cl-hit').dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
const labels={title:'作品名称',eyebrow:'英文副标题',intro:'开场短句',entry:'开始按钮',coastLabel:'海岸 · 章节',coastTitle1:'海岸 · 标题上行',coastTitle2:'海岸 · 标题下行',coastBody1:'海岸 · 正文上行',coastBody2:'海岸 · 正文下行',coastButton:'海岸 · 按钮',duneLabel:'沙丘 · 章节',duneTitle1:'沙丘 · 标题上行',duneTitle2:'沙丘 · 标题下行',duneBody1:'沙丘 · 正文上行',duneBody2:'沙丘 · 正文下行',noteButton:'短笺 · 按钮',noteLabel:'短笺 · 英文',noteTitle:'短笺 · 标题',noteBody1:'短笺 · 正文上行',noteBody2:'短笺 · 正文下行',canyonLabel:'峡谷 · 章节',canyonTitle1:'峡谷 · 标题上行',canyonTitle2:'峡谷 · 标题下行',canyonBody:'峡谷 · 正文',mountainLabel:'换景 · 山按钮',waterLabel:'换景 · 水按钮',skyLabel:'换景 · 天空按钮',mountainTitle:'山 · 图注',waterTitle:'水 · 图注',skyTitle:'天空 · 图注',nightLabel:'星空 · 章节',nightTitle1:'星空 · 标题上行',nightTitle2:'星空 · 标题下行',nightBody1:'星空 · 正文上行',nightBody2:'星空 · 正文下行',starButton:'星空 · 按钮',closing:'结尾短句'};
for(const [key,value]of Object.entries(cfg)){if(typeof value!=='string')continue;const label=document.createElement('label');label.textContent=labels[key]||key;const input=document.createElement('input');input.value=value;input.addEventListener('input',()=>{cfg[key]=input.value;apply()});label.append(input);$('fields').append(label)}
for(const key of Object.keys(cfg.assets)){const label=document.createElement('label');label.textContent='替换图片 · '+({panorama:'整幅景观',night:'星空背景',mountain:'山景卡片',water:'水景卡片',sky:'天空卡片'}[key]);const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif';input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>8*1024*1024){$('status').textContent='请选择小于 8 MB 的图片。';return}const reader=new FileReader();reader.onload=()=>{cfg.assets[key]=reader.result;apply();$('status').textContent='图片已替换，请关闭编辑查看效果。'};reader.readAsDataURL(file)};label.append(input);$('fields').append(label)}
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor.showModal());$('closeEditor').onclick=()=>editor.close();
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
$('saveConfig').onclick=()=>download('config.json',JSON.stringify(cfg,null,2),'application/json');
$('savePage').onclick=()=>{const copy=document.documentElement.cloneNode(true);copy.querySelector('#configData').textContent=JSON.stringify(cfg).replaceAll('<','\\u003c');copy.querySelector('#fields').replaceChildren();copy.querySelector('#editor').removeAttribute('open');copy.querySelector('#cover').removeAttribute('hidden');copy.querySelector('#experience').setAttribute('hidden','');copy.querySelector('#rotateHint').setAttribute('hidden','');download('循光而行-我的版本.html','<!doctype html>\n'+copy.outerHTML,'text/html;charset=utf-8');$('status').textContent='已下载完整页面，文字和图片均已包含。'};
