const cfg=JSON.parse(document.getElementById('configData').textContent);
const $=id=>document.getElementById(id);
const cover=$('cover'),experience=$('experience'),viewport=$('viewport'),editor=$('editor');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function apply(){document.querySelectorAll('[data-key]').forEach(el=>{if(typeof cfg[el.dataset.key]==='string')el.textContent=cfg[el.dataset.key]});for(const [key,value] of Object.entries(cfg.assets)){if(value.startsWith('data:image/')){document.querySelectorAll(`[data-asset="${key}"]`).forEach(el=>el.setAttribute('href',value));if(key==='panorama')document.querySelector('[data-cover]').src=value}}if(reduced)document.querySelectorAll('animate').forEach(el=>el.setAttribute('dur','.001s'))}
apply();
const portrait=()=>matchMedia('(orientation: portrait)').matches;
let readingPosition=0;
function updateProgress(){const vertical=portrait();const length=vertical?viewport.scrollHeight-viewport.clientHeight:viewport.scrollWidth-viewport.clientWidth;readingPosition=length>0?(vertical?viewport.scrollTop:viewport.scrollLeft)/length:0;$('readingProgress').style.transform=`scaleX(${readingPosition})`;document.querySelector('.reading-progress').setAttribute('aria-valuenow',Math.round(readingPosition*100));document.querySelector('.hint').textContent=readingPosition>.99?'旅程到这里，风景仍继续':vertical?'横握手机 · 向上滑动继续':'向左滑动 · 继续探索'}
function resetScroll(){viewport.scrollTop=0;viewport.scrollLeft=0;readingPosition=0;updateProgress()}
let entranceTimer=null;
function openJourney(){if(entranceTimer!==null||cover.hidden)return;experience.hidden=false;resetScroll();if(reduced){cover.hidden=true;return}cover.classList.add('cover-leaving');experience.classList.add('unfolding');entranceTimer=setTimeout(()=>{cover.hidden=true;cover.classList.remove('cover-leaving');experience.classList.remove('unfolding');entranceTimer=null},2400)}
$('enter').onclick=openJourney;
cover.addEventListener('click',e=>{if(!e.target.closest('[data-edit]'))openJourney()});
$('ready').onclick=()=>{$('rotateHint').hidden=true};
$('home').onclick=()=>{clearTimeout(entranceTimer);entranceTimer=null;experience.classList.remove('unfolding');cover.classList.remove('cover-leaving');experience.hidden=true;cover.hidden=false};
$('reset').onclick=()=>{setStars(false);selectView('mountain');showSlide(0);$('cl_note_card').setAttribute('visibility','hidden');document.querySelector('[data-motion="trail"]').setAttribute('visibility','hidden');apply();resetScroll()};
let routeFrame=0,routeLength=0;
function followRoute(){routeFrame=0;const path=$('cl_route');if(!path)return;if(!routeLength)routeLength=path.getTotalLength();const distance=routeLength*Math.max(0,Math.min(1,readingPosition));const point=path.getPointAtLength(distance);$('cl_route_fill').setAttribute('stroke-dasharray',String(routeLength));$('cl_route_fill').setAttribute('stroke-dashoffset',String(routeLength-distance));$('cl_route_marker').setAttribute('transform',`translate(${point.x} ${point.y})`);$('cl_follow_route').setAttribute('visibility','visible')}
function scheduleRoute(){if(!routeFrame)routeFrame=requestAnimationFrame(followRoute)}
viewport.addEventListener('scroll',()=>{updateProgress();scheduleRoute()},{passive:true});
$('enter').addEventListener('click',scheduleRoute);cover.addEventListener('click',scheduleRoute);$('reset').addEventListener('click',scheduleRoute);
viewport.addEventListener('wheel',e=>{if(e.defaultPrevented||portrait()||e.ctrlKey||Math.abs(e.deltaX)>=Math.abs(e.deltaY))return;e.preventDefault();viewport.scrollLeft+=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?viewport.clientWidth:1)},{passive:false});
let drag=null,suppressClick=false;
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('#cl_swipe'))return;if(e.pointerType!=='mouse'||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,moved:false};suppressClick=false});
viewport.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<6)return;drag.moved=true;viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging');if(portrait())viewport.scrollTop=drag.top-dy;else viewport.scrollLeft=drag.left-dx});
function endDrag(e){if(!drag||e.pointerId!==drag.id)return;suppressClick=drag.moved;drag=null;viewport.classList.remove('dragging');if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId)}
viewport.addEventListener('pointerup',endDrag);viewport.addEventListener('pointercancel',endDrag);
viewport.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false}},true);
let previousPortrait=portrait();window.addEventListener('resize',()=>{const nextPortrait=portrait();if(nextPortrait!==previousPortrait){const saved=readingPosition;previousPortrait=nextPortrait;requestAnimationFrame(()=>{viewport.scrollTop=nextPortrait?saved*(viewport.scrollHeight-viewport.clientHeight):0;viewport.scrollLeft=nextPortrait?0:saved*(viewport.scrollWidth-viewport.clientWidth);updateProgress()})}});
viewport.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.cl-hit')){e.preventDefault();e.target.closest('.cl-hit').dispatchEvent(new MouseEvent('click',{bubbles:true}))}});
function selectView(key){for(const name of ['mountain','water','sky']){const active=key===name;$('cl_scene_'+name).setAttribute('visibility',active?'visible':'hidden');document.querySelector(`[data-tab-active="${name}"]`).setAttribute('visibility',active?'visible':'hidden');$('cl_view_'+name).setAttribute('aria-pressed',String(active))}}
function setStars(on){const stars=$('cl_constellation');stars.setAttribute('visibility',on?'visible':'hidden');stars.classList.toggle('is-lit',on);$('cl_star_on').setAttribute('aria-pressed',String(on));document.querySelector('[data-key="starButton"]').textContent=on?'星空已点亮 ✦':cfg.starButton}
viewport.addEventListener('click',e=>{const hit=e.target.closest('.cl-hit');if(!hit)return;const id=hit.id;if(id.startsWith('cl_view_'))selectView(id.slice(8));else if(id==='cl_star_on')setStars(true);else if(id==='cl_star_off')setStars(false);else if(id==='cl_note_open')$('cl_note_card').setAttribute('visibility','visible');else if(id==='cl_note_close')$('cl_note_card').setAttribute('visibility','hidden');else if(id==='cl_depart')document.querySelector('[data-motion="trail"]').setAttribute('visibility','visible');else if(hit.hasAttribute('data-slide-to'))showSlide(Number(hit.dataset.slideTo))});
let slideIndex=0;
function showSlide(index){slideIndex=Math.max(0,Math.min(2,index));document.querySelectorAll('[data-slide]').forEach(el=>{const active=Number(el.dataset.slide)===slideIndex;el.setAttribute('visibility',active?'visible':'hidden');el.classList.toggle('slide-enter',active)});document.querySelectorAll('[data-slide-to]').forEach(el=>{const active=Number(el.dataset.slideTo)===slideIndex;el.setAttribute('aria-pressed',String(active));el.querySelector('circle').setAttribute('r',active?'9':'5')});$('cl_swipe').setAttribute('aria-label',`旅途图文，第${slideIndex+1}张，共3张；上下滑动切换`)}
let cardGesture=null;
const card=$('cl_swipe');
card.addEventListener('pointerdown',e=>{cardGesture={id:e.pointerId,x:e.clientX,y:e.clientY};});
card.addEventListener('pointermove',e=>{if(!cardGesture||cardGesture.id!==e.pointerId)return;const dx=e.clientX-cardGesture.x,dy=e.clientY-cardGesture.y;const cross=portrait()?-dx:dy,along=portrait()?dy:dx;if(Math.abs(cross)>12&&Math.abs(cross)>Math.abs(along)*1.2){card.setPointerCapture(e.pointerId);e.preventDefault()}});
card.addEventListener('pointerup',e=>{if(!cardGesture||cardGesture.id!==e.pointerId)return;const dx=e.clientX-cardGesture.x,dy=e.clientY-cardGesture.y;const cross=portrait()?-dx:dy,along=portrait()?dy:dx;if(Math.abs(cross)>35&&Math.abs(cross)>Math.abs(along)*1.2)showSlide(slideIndex+(cross<0?1:-1));cardGesture=null;if(card.hasPointerCapture(e.pointerId))card.releasePointerCapture(e.pointerId)});
card.addEventListener('pointercancel',()=>{cardGesture=null});
card.addEventListener('keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();showSlide(slideIndex+(e.key==='ArrowDown'?1:-1))}});
let lastCardWheel=0;card.addEventListener('wheel',e=>{if(!portrait()&&!e.ctrlKey&&Math.abs(e.deltaY)>Math.abs(e.deltaX)){const next=slideIndex+(e.deltaY>0?1:-1);if(next>=0&&next<=2){e.preventDefault();if(Date.now()-lastCardWheel>350){showSlide(next);lastCardWheel=Date.now()}}}},{passive:false});
const labels={title:'作品名称',eyebrow:'英文副标题',intro:'开场短句',entry:'开始按钮',coastLabel:'海岸 · 章节',coastTitle1:'海岸 · 标题上行',coastTitle2:'海岸 · 标题下行',coastBody1:'海岸 · 正文上行',coastBody2:'海岸 · 正文下行',coastButton:'海岸 · 按钮',duneLabel:'沙丘 · 章节',duneTitle1:'沙丘 · 标题上行',duneTitle2:'沙丘 · 标题下行',duneBody1:'沙丘 · 正文上行',duneBody2:'沙丘 · 正文下行',noteButton:'短笺 · 按钮',noteLabel:'短笺 · 英文',noteTitle:'短笺 · 标题',noteBody1:'短笺 · 正文上行',noteBody2:'短笺 · 正文下行',canyonLabel:'峡谷 · 章节',canyonTitle1:'峡谷 · 标题上行',canyonTitle2:'峡谷 · 标题下行',canyonBody:'峡谷 · 正文',mountainLabel:'换景 · 山按钮',waterLabel:'换景 · 水按钮',skyLabel:'换景 · 天空按钮',mountainTitle:'山 · 图注',waterTitle:'水 · 图注',skyTitle:'天空 · 图注',nightLabel:'星空 · 章节',nightTitle1:'星空 · 标题上行',nightTitle2:'星空 · 标题下行',nightBody1:'星空 · 正文上行',nightBody2:'星空 · 正文下行',starButton:'星空 · 按钮',closing:'结尾短句'};
Object.assign(labels,{journalLabel:'手记 · 章节',journalTitle:'手记 · 标题',journalCoastTitle:'海风卡片 · 标题',journalCoastBody:'海风卡片 · 正文',journalDuneTitle:'沙丘卡片 · 标题',journalDuneBody:'沙丘卡片 · 正文',journalNightTitle:'夜色卡片 · 标题',journalNightBody:'夜色卡片 · 正文'});
for(const [key,value]of Object.entries(cfg)){if(typeof value!=='string')continue;const label=document.createElement('label');label.textContent=labels[key]||key;const input=document.createElement('input');input.value=value;input.addEventListener('input',()=>{cfg[key]=input.value;apply()});label.append(input);$('fields').append(label)}
for(const key of Object.keys(cfg.assets)){const label=document.createElement('label');label.textContent='替换图片 · '+({panorama:'整幅景观',night:'星空背景',mountain:'山景卡片',water:'水景卡片',sky:'天空卡片'}[key]);const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif';input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>8*1024*1024){$('status').textContent='请选择小于 8 MB 的图片。';return}const reader=new FileReader();reader.onload=()=>{cfg.assets[key]=reader.result;apply();$('status').textContent='图片已替换，请关闭编辑查看效果。'};reader.readAsDataURL(file)};label.append(input);$('fields').append(label)}
const assetNames={panorama:'整幅景观',night:'星空背景',mountain:'山景卡片',water:'水景卡片',sky:'天空卡片',journalCoast:'手记海风',journalDune:'手记沙丘',journalNight:'手记夜色'};
document.querySelectorAll('#fields input[type="file"]').forEach((input,index)=>{const key=Object.keys(cfg.assets)[index];input.parentNode.firstChild.textContent='替换图片 · '+(assetNames[key]||key)});
document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor.showModal());$('closeEditor').onclick=()=>editor.close();
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
$('saveConfig').onclick=()=>download('config.json',JSON.stringify(cfg,null,2),'application/json');
$('savePage').onclick=async()=>{const button=$('savePage');button.disabled=true;$('status').textContent='正在打包图片，请稍候…';try{const exported=JSON.parse(JSON.stringify(cfg));const cache=new Map();for(const [key,value]of Object.entries(exported.assets)){if(value.startsWith('data:'))continue;if(!cache.has(value))cache.set(value,(async()=>{const response=await fetch(value);if(!response.ok)throw new Error('图片下载失败');const blob=await response.blob();return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})})());exported.assets[key]=await cache.get(value)}const copy=document.documentElement.cloneNode(true);copy.querySelector('#configData').textContent=JSON.stringify(exported).replaceAll('<','\\u003c');copy.querySelectorAll('[data-asset]').forEach(el=>el.setAttribute('href',exported.assets[el.dataset.asset]));copy.querySelector('[data-cover]').src=exported.assets.panorama;copy.querySelector('#fields').replaceChildren();copy.querySelector('#editor').removeAttribute('open');copy.querySelector('#cover').removeAttribute('hidden');copy.querySelector('#experience').setAttribute('hidden','');copy.querySelector('#rotateHint').setAttribute('hidden','');download('循光而行-我的版本.html','<!doctype html>\n'+copy.outerHTML,'text/html;charset=utf-8');$('status').textContent='已下载完整页面，文字和图片均已包含。'}catch(error){$('status').textContent='图片暂时未能打包，请网络恢复后重试；也可以先下载配置。'}finally{button.disabled=false}};
